---
- hosts: all  # Target all hosts in your inventory
  become: yes # Required for installing packages (needs root privileges)
  tasks:
    - name: Update apt cache (good practice)
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present # Ensure it's installed
